#! /bin/sh

if [ $(pgrep -cx panel) -gt 1 ] ; then
	printf "%s\n" "The panel is already running." >&2
	exit 1
fi

trap 'trap - TERM; kill 0' INT TERM QUIT EXIT

[ -e "$PANEL_FIFO" ] && rm "$PANEL_FIFO"
mkfifo "$PANEL_FIFO"

# Battery() {
    # BATC="$(cat /sys/class/power_supply/BAT0/capacity)"
    # BATS=/sys/class/power_supply/BAT0/status
    
    # + for charge, - for discharge
    #test "'cat $BATS'" = "Charging" && CAPACITY="+${BATC}%" || CAPACITY="-${BATC}%"
    #sed -n p $CAPACITY
#}

# DateClock() {
    # date '+%m-%d-%y %H:%M'
# }

bspc config top_padding $PANEL_HEIGHT
bspc control --subscribe > "$PANEL_FIFO" &
xtitle -sf 'T%s' > "$PANEL_FIFO" &
clock -sf 'S%a %H:%M' > "$PANEL_FIFO" &

while true; do
      echo "${r}(Battery)" 
      sleep 2;
done > $PANEL_FIFO &

. panel_colors

cat "$PANEL_FIFO" | panel_bar | lemonbar -g x$PANEL_HEIGHT -f $PANEL_FONT_FAMILY -F "$COLOR_FOREGROUND" -B "$COLOR_BACKGROUND" &

wait
