#! /bin/sh

bspc config border_width        5
bspc config top_padding        18
bspc config window_gap          5

bspc config split_ratio         0.50
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_follows_pointer    true
# bspc config normal_border_color "#181512"
# bspc config focused_border_color "00FFFF"
# bspc config presel_border_color "#AC4142"

bspc config normal_frame_opacity 0.0
bspc config focused_frame_opacity 0.05


bspc monitor -d I II III IV V 

bspc rule -a google_chrome_unstable psuedo_tiled=on
bspc rule -a feh manage=off floating=on
bspc rule -a teamviewer floating=on

xrdb ~/.Xresources &
panel &
compton -c &
