#! /bin/sh

PANEL_FONT_FAMILY="Ubuntu Mono:size=11"
ICON_FONT1="FontAwesome:size=11"
ICON_FONT2="fontcustom:size=11"
# PANEL_FONT_FAMILY="Inconsolata:size=10"
# PANEL_FONT_FAMILY="Terminus:size=12"

if [ $(pgrep -cx panel) -gt 1 ] ; then
	printf "%s\n" "The panel is already running." >&2
	exit 1
fi

trap 'trap - TERM; kill 0' INT TERM QUIT EXIT

[ -e "$PANEL_FIFO" ] && rm "$PANEL_FIFO"
mkfifo "$PANEL_FIFO"

Clock() {
    CLK_IC=$(echo -e '\uf017')
    DATE_IC=$(echo -e '\uf073')
    DATE=$(date +"${DATE_IC} %F ${CLK_IC} %l:%M %p")
    echo "$DATE"
}

bspc config top_padding $PANEL_HEIGHT
bspc control --subscribe > "$PANEL_FIFO" &
xtitle -sf 'T%s' > "$PANEL_FIFO" &

while true; do
   echo "S" $(Clock) > "$PANEL_FIFO" &
   sleep 2;
done &

. panel_colors

cat "$PANEL_FIFO" | panel_bar | lemonbar -g x$PANEL_HEIGHT -f "$PANEL_FONT_FAMILY" -f "$ICON_FONT1" -f "$ICON_FONT2" -F "$COLOR_FOREGROUND" -B "$COLOR_BACKGROUND" -u 1

wait
